apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 208445230979.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 208445230979.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 894b0cc3
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
