apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 073660347814.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 073660347814.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: d50c05cd
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
